export const tabs = [
  "Personal Information",
  "Education",
  "Experience",
  "Skills",
  "Projects",
  "Certifications",
  "Links",
];

export const initialProfileForm = {
  fullName: "",
  email: "",
  phone: "",
  location: "",
  targetRole: "",
  summary: "",

  primarySchool: "",
  primaryYear: "",
  secondarySchool: "",
  secondaryYear: "",
  collegeSchool: "",
  collegeDegree: "",
  collegeYear: "",
  vocationalSchool: "",
  vocationalCourse: "",
  vocationalYear: "",
  mastersSchool: "",
  mastersDegree: "",
  mastersYear: "",
  doctoralSchool: "",
  doctoralDegree: "",
  doctoralYear: "",
};

export const normalizeProfile = (profile, fallbackEmail = "") => ({
  fullName: profile?.fullName || "",
  email: profile?.email || fallbackEmail || "",
  phone: profile?.phone || "",
  location: profile?.location || "",
  targetRole: profile?.targetRole || "",
  summary: profile?.summary || "",

  primarySchool: profile?.primarySchool || "",
  primaryYear: profile?.primaryYear || "",
  secondarySchool: profile?.secondarySchool || "",
  secondaryYear: profile?.secondaryYear || "",
  collegeSchool: profile?.collegeSchool || "",
  collegeDegree: profile?.collegeDegree || "",
  collegeYear: profile?.collegeYear || "",
  vocationalSchool: profile?.vocationalSchool || "",
  vocationalCourse: profile?.vocationalCourse || "",
  vocationalYear: profile?.vocationalYear || "",
  mastersSchool: profile?.mastersSchool || "",
  mastersDegree: profile?.mastersDegree || "",
  mastersYear: profile?.mastersYear || "",
  doctoralSchool: profile?.doctoralSchool || "",
  doctoralDegree: profile?.doctoralDegree || "",
  doctoralYear: profile?.doctoralYear || "",
});
