import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { doc,setDoc } from 'firebase/firestore';
const email='portfolio@example.com',password='LocalTest123!';
async function auth(method){return (await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:'+method+'?key=fake-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})})).json();}
let identity=await auth('signUp');if(identity.error?.message==='EMAIL_EXISTS')identity=await auth('signInWithPassword');
const env=await initializeTestEnvironment({projectId:'demo-cvforge',firestore:{host:'127.0.0.1',port:8089}});
const profile={uid:identity.localId,userId:identity.localId,fullName:'Portfolio QA',targetRole:'Data Analyst',summary:'I build SQL reports.',skills:[{skillName:'SQL',category:'Database',proficiencyLevel:'Beginner'}],projects:[{projectTitle:'Reports',description:'I build SQL reports.'}],experience:[],education:{college:[{schoolName:'Test College',degreeProgram:'ICT'}]},certifications:[]};
Object.assign(profile,{email,phone:'+639123456789',location:'Manila'});
Object.assign(profile.projects[0],{role:'Developer',startDate:'2025-01',endDate:'2025-06'});
profile.education.college[0].yearGraduated='2025';
await env.withSecurityRulesDisabled(context=>setDoc(doc(context.firestore(),'profiles',identity.localId),profile));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto('http://127.0.0.1:5173/login');
  await page.evaluate(async({email,password})=>{const {loginWithEmail}=await import('/src/services/authservice.js');await loginWithEmail(email,password,false);},{email,password});
  await page.goto('http://127.0.0.1:5173/web-portfolio');
  await page.getByLabel('Theme Style').selectOption('Modern Blue');
  await page.getByRole('button',{name:'Generate Portfolio',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Review Portfolio Suggestions'});await dialog.waitFor();
  await dialog.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog.getByLabel('Suggested wording').fill('Owner confirmed portfolio introduction.');
  await dialog.getByRole('button',{name:'Approve suggestion',exact:true}).click();
  await dialog.getByRole('button',{name:'Decline',exact:true}).click();
  await dialog.getByRole('button',{name:'Back',exact:true}).click();
  await dialog.getByRole('button',{name:'Decline',exact:true}).click();
  await dialog.getByRole('button',{name:'Create Preview',exact:true}).click();
  await dialog.waitFor({state:'hidden'});
  assert.match(await page.textContent('main'),/Owner confirmed portfolio introduction/);
  assert.match(await page.textContent('main'),/I build SQL reports/);
  assert.equal(await page.locator('[data-theme="modern-blue"]').count(),1);
  await page.getByLabel('Theme Style').selectOption('Minimal White');
  assert.equal(await page.locator('[data-theme="minimal-white"]').count(),1);
  const read=()=>page.evaluate(async()=>{const {auth}=await import('/src/services/firebase.js');const {getProfile}=await import('/src/services/firestoreService.js');window.dispatchEvent(new Event('auth-user-changed'));return getProfile(auth.currentUser.uid);});
  assert.equal((await read()).summary,profile.summary);
  assert.equal(await page.getByRole('button',{name:'Make Public',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Approve for Publishing',exact:true}).click();
  await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()==='Make Public'&&!b.disabled));
  await page.reload();
  await page.locator('[data-theme="minimal-white"]').waitFor();
  await page.getByRole('button',{name:'Make Public',exact:true}).click();
  await page.locator('.swal2-confirm').click();
  await page.getByText('Portfolio Published',{exact:true}).waitFor();
  const slug=await page.evaluate(async()=>{const {auth}=await import('/src/services/firebase.js');const {getWebPortfolioDraft}=await import('/src/services/firestoreService.js');return (await getWebPortfolioDraft(auth.currentUser.uid)).publicSlug;});
  await page.goto('http://127.0.0.1:5173/p/'+slug);
  await page.locator('[data-theme="minimal-white"]').waitFor();
  assert.match(await page.textContent('main'),/Owner confirmed portfolio introduction/);
  assert.deepEqual(errors,[]);
  console.log('PASS: sequential portfolio review/edit/approve/decline/back, preview, profile unchanged, theme switching/persistence and publishing approval gate.');
} finally {await browser.close();await env.cleanup();}
